name: Check PR title

on:
  workflow_call:

jobs:
  check_title:
    uses: ./.github/workflows/check-pr-title-custom.yml
    with:
      task_types: '["build", "feat", "fix", "docs", "test", "ci", "style", "refactor", "perf", "chore", "release"]'
