name: Pre-commit auto-update

on:
  workflow_call:
    inputs:
      sign_commit:
        description: "Sign commit with GPG key"
        required: false
        default: true
        type: boolean
      committer:
        description: "Committer name and email"
        required: true
        type: string
      reviewers:
        description: "Comma-separated list of reviewers"
        required: true
        type: string
    secrets:
      GPG_PRIVATE_KEY:
        required: true
      GPG_PASSPHRASE:
        required: true

jobs:
  auto-update:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.x

      - name: Cache pre-commit environments 💾
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-

      - run: pip install pre-commit
      - run: pre-commit autoupdate --freeze
      - run: pre-commit run --all-files || true

      - uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd # v7.0.0
        if: inputs.sign_commit && github.event_name != 'pull_request'
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        if: always() && github.event_name != 'pull_request'
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        with:
          commit-message: "style: Update pre-commit hooks"
          committer: ${{ inputs.committer }}
          branch: update/pre-commit-hooks
          branch-suffix: timestamp
          delete-branch: true
          title: "style: Update pre-commit hooks"
          body: Update versions of pre-commit hooks to latest version.
          reviewers: ${{ inputs.reviewers }}
