name: Run pre-commit hooks

on:
  workflow_call:
    inputs:
      runs_on:
        description: Runner to run the job on
        required: true
        type: string

      container:
        description: "The container object as a JSON string (leave empty to run natively)"
        required: true
        type: string

jobs:
  run-hooks:
    runs-on: ${{ inputs.runs_on }}
    container: ${{ inputs.container != '' && fromJson(inputs.container) || null }}

    steps:
      - name: Checkout Repo ⚡️
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Cache pre-commit environments 💾
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-

      - name: Prepare runner 🚀
        uses: XRPLF/actions/prepare-runner@e4b6449d55a61c002d7c3fdfa6c20f721ede0606
        with:
          enable_ccache: false

      - name: Run pre-commit ✅
        env:
          MESSAGE: |
            One or more files did not conform to the formatting.
            Maybe you did not enable 'pre-commit' hooks in your local repository?

            To install the `pre-commit` hooks, run: `pre-commit install`

            To run `pre-commit` hooks on all files, run 'pre-commit run --all-files' in the repo.
            Then commit and push the changes.
        run: |
          set +e
          pre-commit run --all-files --show-diff-on-failure --color always --verbose
          rc=$?
          set -e

          if [ $rc -ne 0 ]; then
              # Print the files that changed to give the contributor a hint about
              # what to expect when running `pre-commit` on their own machine.
              git status
              echo "${MESSAGE}"
              exit 1
          fi
