on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  test-pre-commit:
    uses: ./.github/workflows/pre-commit.yml
    with:
      runs_on: ubuntu-latest
      container: '{ "image": "ghcr.io/xrplf/xrpld/pre-commit:latest" }'
