on:
  pull_request:
    paths:
      - ".github/workflows/test-prepare-runner.yml"
      - "prepare-runner/**"
  push:
    branches: [main]
    paths:
      - ".github/workflows/test-prepare-runner.yml"
      - "prepare-runner/**"
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  test-prepare-runner:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: heavy
            container: '{ "image": "ghcr.io/xrplf/xrpld/nix-ubuntu:latest" }'
          - os: heavy-arm64
            container: '{ "image": "ghcr.io/xrplf/xrpld/nix-ubuntu:latest" }'
          - os: macos15
          - os: dev-box-windows-2026

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container != '' && fromJson(matrix.container) || null }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Run prepare-runner action
        uses: ./prepare-runner
        with:
          enable_ccache: false

      - name: Verify ccache is disabled
        shell: bash
        run: |
          if [ "$CCACHE_DISABLE" != "1" ]; then
              echo "CCACHE_DISABLE is not set to 1"
              exit 1
          fi
          echo "CCACHE_DISABLE is correctly set to 1"

      - name: Verify build tools are able to run
        shell: bash
        run: |
          cmake --version
          conan --version
          ccache --version

          if [[ "${{ matrix.os }}" == "macos15" ]]; then
              colima --version
              docker --version
          fi

      - name: Verify Rust tools are able to run
        shell: bash
        run: |
          cargo --version
          rustc --version

          if [[ "${{ runner.os }}" != 'Windows' ]]; then
            cargo audit --version
            cargo clippy --version
            cargo fmt --version
            cargo llvm-cov --version
            cargo nextest --version
          fi
